#pragma config(Motor,  port2,           driveLB,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveRB,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           blade,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*************************************/
/*																	 */
/*		     Activity Fair Bot		     */
/*          With Propellor           */
/*                                   */
/*************************************/


task main()
{
	int Y1 = 0, X1 = 0, threshold = 10;

	while(1 == 1) {
		if(vexRT[Btn6U] == 1) {
			motor[blade] = 70;
		};
		if(vexRT[Btn5U] == 1) {
			motor[blade] = -70;
		};
		//Blade control above, deadsone below
		if(abs(vexRT[Ch2]) > threshold) {
			Y1 = vexRT[Ch2];
		} else {
		Y1 = 0;
	};
		if(abs(vexRT[Ch4]) > threshold) {
			X1 = vexRT[Ch4];
		} else {
		X1 = 0;
	};
		//Drive control below
		int rightPower = (Y1 - X1)*.82;
		int leftPower = (-Y1 - X1)*.82;
		if(rightPower > 127) {
			rightPower = 127;
		} else if(rightPower < -127) {
			rightPower = -127;
		};
		if(leftPower > 127) {
			leftPower = 127;
		} else if(leftPower < -127) {
			leftPower = -127;
		};
		motor[driveRB] = -rightPower;
		motor[driveLB] = -leftPower;
	};
}
